network:
  name: "case14_ieee"
  source: "pglib"
  network_dir: "scripts/grids"

load:
  generator: "precomputed_profile"
  agg_profile: ""
  scenario_file: "exp1/data/precomputed_profiles/case14_ieee/xgb.csv"
  scenarios: 3942
  sigma: 0.00
  change_reactive_power: true
  global_range: 0.4
  max_scaling_factor: 1.2
  step_size: 0.1
  start_scaling_factor: 1.0

topology_perturbation:
  type: "none"

generation_perturbation:
  type: "none"

admittance_perturbation:
  type: "none"

settings:
  num_processes: 8
  data_dir: "data/data_out/xgb"
  large_chunk_size: 2000
  overwrite: true
  mode: "opf"
  include_dc_res: false
  enable_solver_logs: true
  pf_fast: true
  dcpf_fast: true
  max_iter: 200
