admittance_perturbation:
  type: none
generation_perturbation:
  type: none
load:
  agg_profile: ''
  change_reactive_power: true
  generator: precomputed_profile
  global_range: 0.4
  max_scaling_factor: 1.2
  scenario_file: tests/phase1b_1c/tmp/profiles/sarima.csv
  scenarios: 2340
  sigma: 0.0
  start_scaling_factor: 1.0
  step_size: 0.1
network:
  name: case14_ieee
  network_dir: scripts/grids
  source: pglib
settings:
  data_dir: tests/phase1b_1c/tmp/opf_out/sarima
  dcpf_fast: true
  enable_solver_logs: true
  include_dc_res: false
  large_chunk_size: 1000
  max_iter: 200
  mode: opf
  num_processes: 32
  overwrite: true
  pf_fast: true
topology_perturbation:
  type: none
